### ISSUE TITLE
Empty ?

### ISSUE THREAD

**Issue by patobeur** [LordGrrr/Cube-Kicker#1]
il est où le truc ?

**Comment by LordGrrr** [comment]
Qui etes vous ? Que voulez vous? Mais surtout, de quoi parlez-vous?
Laurent BEYSSON
*DigiCraft*
+33 (0)6 41 54 85 12

**Comment by LordGrrr** [comment]
Bluffant l'otamatimse mail/thread!
C'est juste pour un test et me montrer ou y a un truc que tu cherches?
